apiVersion: v1
kind: Service
metadata:
  name: admin-demo
spec:
  selector:
    app: admin
  type: ClusterIP
  ports:
    - port: 8180
      targetPort: 8180
      name: api
    - port: 8181
      targetPort: 8180
      name: management